# Generated by Django 6.0.4 on 2026-04-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentpayment",
            name="is_submitted",
            field=models.BooleanField(default=False, help_text="Submitted by tenant"),
        ),
        migrations.AddField(
            model_name="rentpayment",
            name="payment_details",
            field=models.TextField(
                blank=True, help_text="Details like Transaction ID, etc."
            ),
        ),
    ]
